// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrOtPH7DU1Y66KX7x5k9YtgKe920LHMeU',
    appId: '1:320002721370:web:ee69c8a0ba1f9b6622ba63',
    messagingSenderId: '320002721370',
    projectId: 'borsauygulamasi',
    authDomain: 'borsauygulamasi.firebaseapp.com',
    storageBucket: 'borsauygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw0FB-DpEercq9s7CdTsrQFZ-9FexRgUA',
    appId: '1:320002721370:android:d40df62cc93bef3022ba63',
    messagingSenderId: '320002721370',
    projectId: 'borsauygulamasi',
    storageBucket: 'borsauygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC42zdkr5LspNy30rKixN3Ursp2pfnoA78',
    appId: '1:320002721370:ios:47f83ca63e5a56d022ba63',
    messagingSenderId: '320002721370',
    projectId: 'borsauygulamasi',
    storageBucket: 'borsauygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.borsauygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC42zdkr5LspNy30rKixN3Ursp2pfnoA78',
    appId: '1:320002721370:ios:47f83ca63e5a56d022ba63',
    messagingSenderId: '320002721370',
    projectId: 'borsauygulamasi',
    storageBucket: 'borsauygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.borsauygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrOtPH7DU1Y66KX7x5k9YtgKe920LHMeU',
    appId: '1:320002721370:web:0b5a6e75dffc1f0922ba63',
    messagingSenderId: '320002721370',
    projectId: 'borsauygulamasi',
    authDomain: 'borsauygulamasi.firebaseapp.com',
    storageBucket: 'borsauygulamasi.firebasestorage.app',
  );
}
